config/routes.rb
Rails.application.routes.draw do

    root 'static_pages#home'
    get 'contacto' => 'static_pages#contact', as: :contact
    get 'platillos' => 'static_pages#dishes', as: :dishes
    get 'eventos' => 'static_pages#events', as: :events
    get 'quienes-somos' => 'static_pages#about', as: :about
    get 'platillos/bocadillos' => 'dishes#snack', as: :snacks
    get 'platillos/cremas' => 'dishes#cream', as: :creams
    get 'platillos/postres' => 'dishes#dessert', as: :dessert
    get 'platillos/gourmet' => 'dishes#elegant', as: :gourmet
    get 'platillos/fuertes' => 'dishes#main', as: :main
    get 'platillos/pates' => 'dishes#pate', as: :pates
    get 'platillos/ensaladas' => 'dishes#salad', as: :salad

end

app/models/contact_form.rb
class ContactForm < MailForm::Base

  attribute :email,:validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :name, :validate => :true

  def headers
    {
      :subject => "Mensaje de la pagina de elbuenplato.com",
      :to => "atrejo@elbuenplato.com",
      :from => %("#{name}" <#{email}>)
    }
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :history

  private

  def history
    session[:history] = session[:history].to_i + 1
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  def snack
  end

  def dessert
  end

  def elegant
  end

  def main
  end

  def entry
  end

  def salad
  end

  def cream
  end

  def pate
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  include ActionView::Helpers::TextHelper

  def home
  end

  def contact
    unless params.blank? 
      c = ContactForm.new(:name => params["name"],:email => params["email"], :message => params["message"])
      if c.deliver

        begin

          account_sid = ENV['TWILIO_ACCOUNT_SID']
          auth_token  = ENV['TWILIO_AUTH_TOKEN']
          client = Twilio::REST::Client.new account_sid, auth_token

          from = "+16096442390" # Your Twilio number

          friends = {
            "+5218113129230" => "Gilberto",
            "+5218111899317" => "Abril"
          }
          friends.each do |key, value|
            client.account.messages.create(
              :from => from,
              :to => key,
              :body => "Tienes un email de #{params["name"]} y dice, #{truncate(params["message"], length: 100)}"
            ) 
            puts "\n\n Sent message to #{value}"
          end
        rescue Twilio::REST::RequestError => e
          puts e.message
        end

        redirect_to root_path
      end
    end
  end

  def dishes
  end

  def about
  end

  def events
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def title(page_title)
    content_for :title, t(page_title.to_s)
  end

end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/dishes/cream.html.erb
<%= render "share/data" %>
<%= content_for :stylesheet do %>
<%= stylesheet_link_tag "single_gallery" %>
<% end %>

<%= content_for :javascript do %>

  <%= javascript_include_tag "jquery.carouFredSel-6.0.4-packed" %>

        <script type="text/javascript">
          $(function() {

            $('#carousel').carouFredSel({
              responsive: true,
              circular: false,
              auto: false,
              items: {
                visible: 1,
                width: 200,
                height: '56%'
              },
              scroll: {
                fx: 'directscroll'
              }
            });

            $('#thumbs').carouFredSel({
              responsive: true,
              circular: false,
              infinite: false,
              auto: false,
              prev: '#prev',
              next: '#next',
              items: {
                visible: {
                  min: 2,
                  max: 4
                },
                width: 202,
                height: '66%'
              }
            });

            $('#thumbs a').click(function() {
              $('#carousel').trigger('slideTo', '#' + this.href.split('#').pop() );
              $('#thumbs a').removeClass('selected');
              $(this).addClass('selected');
              return false;
            });

          });
        </script>
<% end %>
      
<div class="container single-gallery">
  <div class="row-fluid">
    <div id="wrapper">
      <div id="carousel-wrapper">
        <%= image_tag "img/gui/carousel_shadow.png", :id => "shadow" %>
        <div id="carousel">
          <span id="slide-1"><img src="/assets/dishes/creams/picture1.jpg" alt="Cream" /></span>
          <span id="slide-2"><img src="/assets/dishes/creams/picture2.jpg" alt="Cream" /></span>
          <span id="slide-3"><img src="/assets/dishes/creams/picture3.jpg" alt="Cream" /></span>
          <span id="slide-4"><img src="/assets/dishes/creams/picture4.jpg" alt="Cream" /></span>
        </div>
      </div>
      <div id="thumbs-wrapper">
        <div id="thumbs">
          <a href="#slide-1" class="selected"><img src="/assets/dishes/creams/picture1.jpg" alt="Cream" /></a>
          <a href="#slide-2"><img src="/assets/dishes/creams/picture2.jpg" alt="Cream" /></a>
          <a href="#slide-3"><img src="/assets/dishes/creams/picture3.jpg" alt="Cream" /></a>
          <a href="#slide-4"><img src="/assets/dishes/creams/picture4.jpg" alt="Cream" /></a>
        </div>
        <a id="prev" href="#"></a>
        <a id="next" href="#"></a>
      </div>
    </div>
  </div>
</div>

app/views/dishes/dessert.html.erb
<%= render "share/data" %>
<%= content_for :stylesheet do %>
<%= stylesheet_link_tag "single_gallery" %>
<% end %>

<%= content_for :javascript do %>

  <%= javascript_include_tag "jquery.carouFredSel-6.0.4-packed" %>

        <script type="text/javascript">
          $(function() {

            $('#carousel').carouFredSel({
              responsive: true,
              circular: false,
              auto: false,
              items: {
                visible: 1,
                width: 200,
                height: '56%'
              },
              scroll: {
                fx: 'directscroll'
              }
            });

            $('#thumbs').carouFredSel({
              responsive: true,
              circular: false,
              infinite: false,
              auto: false,
              prev: '#prev',
              next: '#next',
              items: {
                visible: {
                  min: 2,
                  max: 4
                },
                width: 202,
                height: '66%'
              }
            });

            $('#thumbs a').click(function() {
              $('#carousel').trigger('slideTo', '#' + this.href.split('#').pop() );
              $('#thumbs a').removeClass('selected');
              $(this).addClass('selected');
              return false;
            });

          });
        </script>



<% end %>
      
<div class="container single-gallery">
  <div class="row-fluid">
    <div id="wrapper">
      <div id="carousel-wrapper">
        <%= image_tag "img/gui/carousel_shadow.png", :id => "shadow" %>
        <div id="carousel">
          <span id="slide-1"><img src="/assets/dishes/desserts/crepas_1024.jpg" alt="Crepa" /></span>
          <span id="slide-2"><img src="/assets/dishes/desserts/crepa_1_1024.jpg" alt="Crepa" /></span>
          <span id="slide-3"><img src="/assets/dishes/desserts/pari_&_brest_con_fruta_1024.jpg" alt="Pari & brest con fruta" /></span>
          <span id="slide-4"><img src="/assets/dishes/desserts/helado_con_salsa_de_Fresa_1024.jpg" alt="Helado con salsa de fresa" /></span>
          <span id="slide-5"><img src="/assets/dishes/desserts/helado_a_la_moda_1024.jpg" alt="Helado a la moda" /></span>
          <span id="slide-6"><img src="/assets/dishes/desserts/Brownie_1024.jpg" alt="Brownie" /></span>
          <span id="slide-7"><img src="/assets/dishes/desserts/flan_1024.jpg" alt="Flan" /></span>
          <span id="slide-8"><img src="/assets/dishes/desserts/tartaleta_de_frutas_1024.jpg" alt="Tartaletas de frutas" /></span>
          <span id="slide-9"><img src="/assets/dishes/desserts/choox_con_crema_pastelera_y_frutas_1024.jpg" alt="Choox con crema pastelera y frutas" /></span>
          <span id="slide-10"><img src="/assets/dishes/desserts/tartaleta_1024.jpg" alt="Tartaleta de mango" /></span>
          <span id="slide-11"><img src="/assets/dishes/desserts/pareja_de_cisnes_para_bodas_1024.jpg" alt="Pareja de cisnes para bodas" /></span>
          <span id="slide-12"><img src="/assets/dishes/desserts/pastel_de_queso_1024.jpg" alt="Pastel de queso" /></span>
          <span id="slide-13"><img src="/assets/dishes/desserts/tartaleta_de_manzana_1024.jpg" alt="Tartaleta de manzana" /></span>
          <span id="slide-14"><img src="/assets/dishes/desserts/choox_rellenos_1024.jpg" alt="Choox rellenos" /></span>
          <span id="slide-15"><img src="/assets/dishes/desserts/tartaleta_de_mango_1024.jpg" alt="Tartaleta de mango" /></span>
        </div>
      </div>
      <div id="thumbs-wrapper">
        <div id="thumbs">
          <a href="#slide-1" class="selected"><img src="/assets/dishes/desserts/crepas_216.jpg" alt="Crepa" /></a>
          <a href="#slide-2"><img src="/assets/dishes/desserts/crepa_1_216.jpg" alt="Crepa" /></a>
          <a href="#slide-3"><img src="/assets/dishes/desserts/pari_&_brest_con_fruta_216.jpg" alt="Pari & brest con fruta" /></a>
          <a href="#slide-4"><img src="/assets/dishes/desserts/helado_con_salsa_de_Fresa_216.jpg" alt="Helado de fresa" /></a>
          <a href="#slide-5"><img src="/assets/dishes/desserts/helado_a_la_moda_216.jpg" alt="Helado a la moda" /></a>
          <a href="#slide-6"><img src="/assets/dishes/desserts/Brownie_216.jpg" alt="Brownie" /></a>
          <a href="#slide-7"><img src="/assets/dishes/desserts/flan_216.jpg" alt="Flan" /></a>
          <a href="#slide-8"><img src="/assets/dishes/desserts/tartaleta_de_frutas_216.jpg" alt="Tartaletas de frutas"  /></a>
          <a href="#slide-9"><img src="/assets/dishes/desserts/choox_con_crema_pastelera_y_frutas_216.jpg" alt="Choox con crema pastelera y frutas" /></a>
          <a href="#slide-10"><img src="/assets/dishes/desserts/tartaleta_216.jpg" alt="Tartaleta de mango" /></a>
          <a href="#slide-11"><img src="/assets/dishes/desserts/pareja_de_cisnes_para_bodas_216.jpg" alt="Parajea de cisnes para bodas" /></a>
          <a href="#slide-12"><img src="/assets/dishes/desserts/pastel_de_queso_216.jpg" alt="Pastel de queso" /></a>
          <a href="#slide-13"><img src="/assets/dishes/desserts/tartaleta_de_manzana_216.jpg" alt="Tartaleta de manzana" /></a>
          <a href="#slide-14"><img src="/assets/dishes/desserts/choox_rellenos_216.jpg" alt="Choox rellenos" /></a>
          <a href="#slide-15"><img src="/assets/dishes/desserts/tartaleta_de_mango_216.jpg" alt="Tartaleta de mango" /></a>
        </div>
        <a id="prev" href="#"></a>
        <a id="next" href="#"></a>
      </div>
    </div>
  </div>
</div>

app/views/dishes/elegant.html.erb
<%= render "share/data" %>
<%= content_for :stylesheet do %>
<%= stylesheet_link_tag "single_gallery" %>
<% end %>

<%= content_for :javascript do %>

  <%= javascript_include_tag "jquery.carouFredSel-6.0.4-packed" %>

        <script type="text/javascript">
          $(function() {

            $('#carousel').carouFredSel({
              responsive: true,
              circular: false,
              auto: false,
              items: {
                visible: 1,
                width: 200,
                height: '56%'
              },
              scroll: {
                fx: 'directscroll'
              }
            });

            $('#thumbs').carouFredSel({
              responsive: true,
              circular: false,
              infinite: false,
              auto: false,
              prev: '#prev',
              next: '#next',
              items: {
                visible: {
                  min: 2,
                  max: 4
                },
                width: 202,
                height: '66%'
              }
            });

            $('#thumbs a').click(function() {
              $('#carousel').trigger('slideTo', '#' + this.href.split('#').pop() );
              $('#thumbs a').removeClass('selected');
              $(this).addClass('selected');
              return false;
            });

          });
        </script>



<% end %>
      
<div class="container single-gallery">
  <div class="row-fluid">
    <div id="wrapper">
      <div id="carousel-wrapper">
        <%= image_tag "img/gui/carousel_shadow.png", :id => "shadow" %>
        <div id="carousel">
          <span id="slide-1"><img src="/assets/dishes/gourmet/chiles_nogada_1024.jpg" alt="Chiles estilo nogada" /></span>
          <span id="slide-2"><img src="/assets/dishes/gourmet/envuelto_de_ave_1024.jpg" alt="Envuelto de ave" /></span>
          <span id="slide-3"><img src="/assets/dishes/gourmet/mar_y_tierra_1024.jpg" alt="Mar y tierra" /></span>
          <span id="slide-4"><img src="/assets/dishes/gourmet/medio_aguacate_1024.jpg" alt="Medio aguacate" /></span>
          <span id="slide-5"><img src="/assets/dishes/gourmet/camarones_al_coco_1024.jpg" alt="Camorones al coco" /></span>
          <span id="slide-6"><img src="/assets/dishes/gourmet/filete_chateaubriand_1024.jpg" alt="Filete chateaubriand" /></span>
          <span id="slide-7"><img src="/assets/dishes/gourmet/filete_de_res_y_medallon_de_pollo_1024.jpg" alt="Filete de res y medallon de pollo" /></span>
          <span id="slide-8"><img src="/assets/dishes/gourmet/medallon_de_res_1024.jpg" alt="Medallon de res" /></span>
        </div>
      </div>
      <div id="thumbs-wrapper">
        <div id="thumbs">
          <a href="#slide-1" class="selected"><img src="/assets/dishes/gourmet/chiles_nogada_216.jpg" alt="Chiles estilo nogada" /></a>
          <a href="#slide-2"><img src="/assets/dishes/gourmet/envuelto_de_ave_216.jpg" alt="Envuelto de ave" /></a>
          <a href="#slide-3"><img src="/assets/dishes/gourmet/mar_y_tierra_216.jpg" alt="Mar y Tierra" /></a>
          <a href="#slide-4"><img src="/assets/dishes/gourmet/medio_aguacate_216.jpg" alt="Medio aguacate" /></a>
          <a href="#slide-5"><img src="/assets/dishes/gourmet/camarones_al_coco_216.jpg" alt="Camarones al coco" /></a>
          <a href="#slide-6"><img src="/assets/dishes/gourmet/filete_chateaubriand_216.jpg" alt="Filete chateaubriand" /></a>
          <a href="#slide-7"><img src="/assets/dishes/gourmet/filete_de_res_y_medallon_de_pollo_216.jpg" alt="Filete de res y medallon de pollo" /></a>
          <a href="#slide-8"><img src="/assets/dishes/gourmet/medallon_de_res_216.jpg" alt="Medallon de res"  /></a>
        </div>
        <a id="prev" href="#"></a>
        <a id="next" href="#"></a>
      </div>
    </div>
  </div>
</div>

app/views/dishes/entry.html.erb
<h1>Dishes#entry</h1>
<p>Find me in app/views/dishes/entry.html.erb</p>

app/views/dishes/pate.html.erb
<%= render "share/data" %>
<%= content_for :stylesheet do %>
<%= stylesheet_link_tag "single_gallery" %>
<% end %>

<%= content_for :javascript do %>

  <%= javascript_include_tag "jquery.carouFredSel-6.0.4-packed" %>

        <script type="text/javascript">
          $(function() {

            $('#carousel').carouFredSel({
              responsive: true,
              circular: false,
              auto: false,
              items: {
                visible: 1,
                width: 200,
                height: '56%'
              },
              scroll: {
                fx: 'directscroll'
              }
            });

            $('#thumbs').carouFredSel({
              responsive: true,
              circular: false,
              infinite: false,
              auto: false,
              prev: '#prev',
              next: '#next',
              items: {
                visible: {
                  min: 2,
                  max: 4
                },
                width: 202,
                height: '66%'
              }
            });

            $('#thumbs a').click(function() {
              $('#carousel').trigger('slideTo', '#' + this.href.split('#').pop() );
              $('#thumbs a').removeClass('selected');
              $(this).addClass('selected');
              return false;
            });

          });
        </script>
<% end %>
      
<div class="container single-gallery">
  <div class="row-fluid">
    <div id="wrapper">
      <div id="carousel-wrapper">
        <%= image_tag "img/gui/carousel_shadow.png", :id => "shadow" %>
        <div id="carousel">
          <span id="slide-1"><img src="/assets/dishes/pates/picture1.jpg" alt="Pates" /></span>
          <span id="slide-2"><img src="/assets/dishes/pates/picture2.jpg" alt="Pates" /></span>
        </div>
      </div>
      <div id="thumbs-wrapper">
        <div id="thumbs">
          <a href="#slide-1" class="selected"><img src="/assets/dishes/pates/picture1.jpg" alt="Pates" /></a>
          <a href="#slide-2"><img src="/assets/dishes/pates/picture2.jpg" alt="Pates" /></a>
        </div>
        <a id="prev" href="#"></a>
        <a id="next" href="#"></a>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header_bar.html.erb
<div class="container-fluid topStrip">
  <div class="container">
    <div class="row-fluid">
      <div class="span7 topAddress">
        <p>Monterrey,Nuevo León, Tel. 81023413, 8111530834 o 8111899317</p>
      </div>
      <div class="span5">
        <ul id="social-icons">
          <li>
          <a href="#" title="Follow us on Facebook" target="_blank" class="ico-1">Link</a>
          </li>
          <li>
          <a href="#" title="Follow us on Twitter" target="_blank" class="ico-2">Link</a>
          </li>
          <li>
          <a href="#" title="Follow us on Vimeo" target="_blank" class="ico-3">Link</a>
          </li>
          <li>
          <a href="#" title="Follow us on LinkedIn" target="_blank" class="ico-4">Link</a>
          </li>
        </ul>
      </div>
    </div> 
  </div>
</div>

app/views/layouts/_navigation.html.erb
<div <%= " id='aboutNavigation' ".html_safe unless current_page?(root_path) %> class="container logo-nav">
  <div class="row-fluid">
    <div class="span12">
      <%= link_to image_tag("logo_trans.png", :alt => "California Logo", :width => "273", :height =>"184"), root_path, :title => "Homepage", :class => "logoHolder"%> 
    </div>
    <div class="row-fluid">
      <div class="span12 main-nav">
        <button class="smallScreenNav">Menu</button>
        <ul class="smallNavMenu">
          <li><%= link_to "Inicio",root_path %> </li>
          <li><%= link_to "Quienes somos",about_path %></li>
          <li><%= link_to "Platillos", dishes_path  %></li>
          <li><%= link_to "Contacto", contact_path %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/contact.html.erb
<%= render 'share/data' %>

<!-- Contact Section -->

<div class="container aboutWrapper reservationsWrapper">
  <div class="row-fluid client_info_holder animationStart section_featured_texts">
    <div class="span12 reservations-title">
      <h2><%= t :contact %></h2>
    </div>
  </div>

  <div class="divider divider_contact"></div>

  <div class="row-fluid reservations-features client_info_holder animationStart section_featured_texts">
    <p>Contactanos atravez de este formulario, escribenos alguna opnion, pregunta, duda o comentario y con gusto te atenderemos o bien a nuestros telefonos 81023413, 8111530834 o 8111899317 </p>
    <%= form_tag(contact_path, :method => "get", :multipart => false,:class => "client_info_holder animationStart section_featured_texts") do %>
      <div class="row-fluid inputWrapper">
        <div class="span6">
          <p>
          <label for="name"><%= t :name %></label>
          <%= text_field_tag "name", nil, :id=>"name", :placeholder => "Tu nombre" %>
          </p>
        </div>
        <div class="span6">
          <p>
          <label for="last-name">Email</label>
          <%= text_field_tag "email", nil, :id=>"email", :placeholder => "Tu correo" %>
          </p>
        </div>

        <div class="row-fluid">
          <div class="span12 messageContainer">
            <label for="message"><%= t :message %></label>
            <%= text_area_tag "message", nil, :id => "message", :placeholder => "Tus dudas o comentarios, etc.", :cols => "30", :rows => "10" %>
          </div>
        </div>
        <%= submit_tag "Enviar" %> 
      <%end%>
      </div>
    </form>
  </div>
</div>

app/views/static_pages/dishes.html.erb
<%= title(:dishes) %>
<%= render "share/data" %>
<%= content_for :metadata do %>
  <meta property="og:url" content="<%= dishes_url %>" /> 
  <meta property="og:title" content="<%= t :dishes %>" /> 
  <meta property="og:description" content="Descubre nuestros platillos para tu evento, cremas, postres, 3 tiempos, etc. Contanctanos, pregunta por precios otros platillos,  cualquier duda o comentario a contacto@elbuenplato.com nuestros telefonos 81023413, 8111530834 o 8111899317" /> 
  <meta property="og:image" content="<%= asset_url "dishes/gourmet/face_book.jpg" %>" /> 
<% end %>

<!-- Gallery Posts -->
<div class="container gallery-wrapper">
  <div class="row-fluid">


    <div class="span6 client_info_holder animationStart section_featured_texts gallery-post">
      <a class="paperStack" href="platillos/gourmet">
        <img src="/assets/dishes/gourmet/chiles_nogada_428.jpg" alt="Chiles estilo nogada platillo gourmet">
      </a>
      <div class="gallery-postinfo">
        <h3><%= link_to "Gourmet", gourmet_path %></h3>
        <div class="postinfo">
          <p>18.05.2014</p>
        </div>
        <p>Platillos con una elaboración mas refinada con ingredientes exquisitamente seleccionados; para aquellos con una pasión por las complejidades de la comida gastronómica. </p>
        <button><%= link_to t(:open_gallery), gourmet_path %></button>
      </div>
    </div>



    <div class="span6 client_info_holder animationStart section_featured_texts gallery-post">
      <a class="paperStack" href="platillos/postres">
        <img src="/assets/dishes/desserts/crepas_428.jpg" alt="Crepas postres">
      </a>
      <div class="gallery-postinfo">
        <h3><%= link_to t(:desserts), dessert_path %></h3>
        <div class="postinfo">
          <p>18.05.2014</p>
        </div>
        <p>No hay mejor manera de acabar una buena cena que saboreando un delicioso postre. 
        Si quieres sorprender a tus invitados toma nota de las últimas tendencias en postres. </p>
        <button><%= link_to t(:open_gallery), dessert_path %></button>
      </div>
    </div>



    <div class="span6 client_info_holder animationStart section_featured_texts gallery-post">
      <a class="paperStack" href="platillos/fuertes">
        <img src="assets/dishes/mains/medallon_de_pollo_en_salsa_de_cilantro_428.jpg" alt="Medallon de pollo en salsa de cilantro">
      </a>
      <div class="gallery-postinfo">
        <h3><%= link_to t(:main), main_path %></h3>
        <div class="postinfo">
          <p>18.05.2014</p>
        </div>
        <p>
          Sin importar si es Filete de Res o Suprema de ave entre otros,  las personas buscamos comer algo delicioso en nuestro evento ya sea Boda,XV o cualquier otra celebración y no pasar por alto que este tenga la armonía con todo lo que estamos ofreciendo en este día  tan especial , por algo se le llama platillo principal.
          </p>
        <button><%= link_to t(:open_gallery), main_path %></button>
      </div>
    </div>




    <div class="span6 client_info_holder animationStart section_featured_texts gallery-post">
      <a class="paperStack" href="platillos/ensaladas">
        <img src="assets/dishes/salads/ensalada_tres_lechugas_428.jpg" alt="Ensalda tres lechugas">
      </a>
      <div class="gallery-postinfo">
        <h3><%= link_to t(:salads), salad_path %></h3>
        <div class="postinfo">
          <p>19.05.2014</p>
        </div>
        <p>
        Las ensaladas, nos hace ver la complejidad a la que pueden llegar este tipo de alimentos, pese a la simplicidad de su apariencia estos platillos es tendencia en xv para la sección de jóvenes o si los invitados a tu evento requieren algo más fresco light.</p>
        <button><%= link_to t(:open_gallery), salad_path %></button>
      </div>
    </div>


    <div class="span6 client_info_holder animationStart section_featured_texts gallery-post">
      <a class="paperStack" href="platillos/bocadillos">
        <img src="assets/dishes/snacks/charola_de_bocadillos_428.jpg" alt="Charola de bocadillos">
      </a>
      <div class="gallery-postinfo">
        <h3><%= link_to t(:snacks), snacks_path %></h3>
        <div class="postinfo">
          <p>19.05.2014</p>
        </div>
        <p>
        Los bocadillos con el tiempo ha evolucionado hasta convertirse ícono de cualquier evento o reunión en modo de tentempié o aperitivo, que suele consistir en una trozo de pan de tamaño variable, abierto en dos mitades, y entre cuyas mitades se coloca cualquier alimento diferente al propio pan; como embutido, queso, pescado e incluso frutas.
        </p>
        <button><%= link_to t(:open_gallery), snacks_path %></button>
      </div>
    </div>




    <div class="span6 client_info_holder animationStart section_featured_texts gallery-post">
      <a class="paperStack" href="platillos/cremas">
        <img src="assets/dishes/creams/crema_de_brocoli_con_crotones_428.jpg" alt="Crema de brocoli con crotones">
      </a>
      <div class="gallery-postinfo">
        <h3><%= link_to t(:creams), creams_path %></h3>
        <div class="postinfo">
          <p>19.05.2014</p>
        </div>
        <p>
        Platillo de entrada que consta de una familia de preparaciones de varios vegetales que dan como resultado una consistencia cremosa, y la puedas deleitar en su variedad de sabores, para que tu evento cuente con un Banquete ideal y tus invitados se lleven un buen sabor a su paladar.
        </p>
        <button><%= link_to t(:open_gallery), creams_path %></button>
      </div>
    </div>



    <div class="span6 client_info_holder animationStart section_featured_texts gallery-post">
      <a class="paperStack" href="platillos/pates">
        <img src="assets/dishes/pates/pate_de_la_casa_428.jpg" alt="Patés de la casa">
      </a>
      <div class="gallery-postinfo">
        <h3><%= link_to "Pates", pates_path %></h3>
        <div class="postinfo">
          <p>19.05.2014</p>
        </div>
        <p>
        Platillo considerado como aperitivo generalmente  untables, elaborado de queso o distintos ingredientes y variedad de presentaciones para cualquier exigencia de cliente  e invitado.
        </p>
        <button><%= link_to t(:open_gallery), pates_path %></button>
      </div>
    </div>




  </div>
</div>

app/views/static_pages/news.html.erb
<h1>Home#news</h1>
<p>Find me in app/views/home/news.html.erb</p>